title: Data Rescue Boston
description: Data Rescue Boston
baseurl: ""
url: "https://datarescue-boston.github.io"

collections:
  - sections
  - meetings

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
